--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Cosmoverse/Waypoint
build-by-default: true
branches:
- master
projects:
  Waypoint:
    path: ""
    icon: icon.png
    libs:
      - src: cosmoverse/awaitform/AwaitForm
        version: ^0.0.2
      - src: poggit/libasynql/libasynql
        version: ^4.2.3
      - src: SOF3/await-generator/await-generator
        version: ^3.6.1
...
